version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/c7-systemd
    ports:
      - "6666:6666"
    volumes:
      - ./data:/work
    # 以下のエラーに対応するために追記
    # D-Bus connection: Operation not permitted
